<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: bundito
 * Date: Mon, 28 Aug 2017 12:27:07 -0500
 */

$conf['title'] = 'KAG Productions';
$conf['template'] = 'adoradark';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['mailfrom'] = 'bundito@gmail.com';
$conf['plugin']['authmysql']['TablesToLock'] = array();
$conf['plugin']['swiftmail']['smtp_host'] = 'smtp.gmail.com';
$conf['plugin']['swiftmail']['smtp_port'] = 465;
$conf['plugin']['swiftmail']['smtp_ssl'] = '2';
$conf['plugin']['swiftmail']['auth_user'] = 'bundito@gmail.com';
$conf['plugin']['swiftmail']['auth_pass'] = 'D1t0google02';
$conf['plugin']['swiftmail']['debug'] = 1;
$conf['plugin']['smtp']['smtp_port'] = 465;
$conf['plugin']['smtp']['smtp_ssl'] = 'tls';
$conf['plugin']['smtp']['auth_user'] = 'bundito@gmail.com';
$conf['plugin']['smtp']['auth_pass'] = 'D1t0google02';
$conf['plugin']['smtp']['debug'] = 1;

// end auto-generated content
